name: Android Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - name: Run Tests
        run: ./gradlew test

      - name: Run Detekt
        uses: gradle/gradle-build-action@v1
        with:
          arguments: detekt

      - name: Assemble app
        uses: gradle/gradle-build-action@v1
        with:
          arguments: assembleDebug --stacktrace

      - name: Build Project
        run: ./gradlew assemble

